### ISSUE TITLE
Crashing on import? 

### ISSUE THREAD

**Issue by Trendkillgaming** [ko-vasilev/Hearthstone-Collection-Tracker#36]
###### #### 10/9/2015 2:07:42 AM

System.MissingMethodException: Method not found: 'Hearthstone_Deck_Tracker.MainWindow Hearthstone_Deck_Tracker.Helper.get_MainWindow()'.
   at Hearthstone_Collection_Tracker.Internal.Importing.HearthstoneImporter.ShowHDTOverlay()
   at Hearthstone_Collection_Tracker.Internal.Importing.HearthstoneImporter.<Import>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hearthstone_Collection_Tracker.SettingsWindow.<ButtonImportFromGame_Click>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

now sure what to do?

**Comment by scottismyname** [comment]
Confirmed broken with HDT 0.11.5.  Note from epix in my thread over there:

`HearthstoneImporter.ShowHDTOverlay() and HearthstoneImporter.HideHDTOverlay() need to use API.Core.OverlayWindow rather than Helper.MainWindow.Overlay.`

The new API endpoint is only available in pre-release v0.11.5 and will therefore obviously not be compatible with the current live release. I plan on releasing v0.11.6 (as an actual release) some time around sunday/monday.

**Comment by Trendkillgaming** [comment]
oh okay, thanks. I thought I had done something incorrectly. look forward to the update!

**Comment by rafx85** [comment]
Any info about updates?

**Comment by hussein1128** [comment]
collection tracker is still crashing, waiting for the update, now HDT is updated and the colection tracker is out dated, fix this guys

**Comment by ko-vasilev** [comment]
Will update shortly.
