### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by RyenNelsen** [ko-vasilev/Hearthstone-Collection-Tracker#6]
The plugin fails to load with a pre-compiled **Hearthstone Deck Tracker v0.10.1.0**.

Error:

```
[12:23:45 PM] PluginManager: Error Loading C:\Users\Ryen\Desktop\Hearthstone Deck Tracker\Plugins\Hearthstone Collection Tracker.dll:
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\Ryen\Desktop\Hearthstone Deck Tracker\Plugins\Hearthstone Collection Tracker.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Users\Ryen\Desktop\Hearthstone Deck Tracker\Plugins\Hearthstone Collection Tracker.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Hearthstone_Deck_Tracker.Plugins.PluginManager.GetModule(String pFileName, Type pTypeInterface)

```

**Comment by azeier** [comment]
https://github.com/ko-vasilev/Hearthstone-Collection-Tracker#installation this should fix your problem

**Comment by RyenNelsen** [comment]
Whoops, definitely a RTFM fail. The download on HDT's page bypasses the installation steps. Thanks!
